services:
  postgres:
    image: postgres:16-alpine
    container_name: e21-postgres
    environment:
      POSTGRES_DB: e2e
      POSTGRES_USER: e2e
      POSTGRES_PASSWORD: e2e
    ports:
      - "5432:5432"
    volumes:
      - e21-postgres-data:/var/lib/postgresql/data

volumes:
  e21-postgres-data:
