spring.application.name=lab-e2e-01

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:e2e}
spring.datasource.username=${DB_USER:e2e}
spring.datasource.password=${DB_PASSWORD:e2e}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
